name: Codecov
on:
  push:
    branches: [main]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p 'test_*.py'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
